# Big Bot Configuration File
# This file contains all the settings for the Big Bot Mumble bot.
# You can override most of these settings using command-line arguments.

# Bot-specific settings
bot:
  # The username the bot will use when connecting to the server
  username: "Big Bot"
  # Optional password for server authentication (leave as null if not needed)
  password: null
  # Enable verbose logging (can be overridden with --verbose)
  verbose: false

# Mumble server connection settings  
server:
  # Hostname or IP address of the Mumble server
  host: "mumble.example.com"
  # Port number for the Mumble server (default: 64738)
  port: 64738
  # Connection timeout in seconds
  timeout_seconds: 10

# Bot behavior settings
behavior:
  # Greeting sounds when users join
  # Options: "all" (custom + random fallback), "custom" (only user-set), "none" (silent)
  auto_greetings: all
  # Farewell sounds when users leave  
  # Options: "all" (custom + random fallback), "custom" (only user-set), "none" (silent)
  auto_farewells: custom
  # Allow users to send commands via private messages
  allow_private_commands: true
  # Global volume multiplier for all outgoing audio (1.0 = normal, 0.5 = half volume, 2.0 = double volume)
  volume: 1.0
  # Enable volume normalization to maintain consistent loudness levels
  volume_normalization_enabled: false
  # Target loudness level for normalization (in LUFS, typically -23 to -16)
  target_loudness_lufs: -18.0
  # Maximum gain boost allowed during normalization (in dB, prevents over-amplification)
  max_normalization_gain_db: 12.0
  # Enable random audio effects when playing sounds
  random_modifiers_enabled: true
  # Probability (0.0-1.0) for each round of random modifier application (0.05 = 5% chance)
  random_modifier_chance: 0.05
  # Number of rounds to potentially apply random modifiers (2 = two 5% chances)
  random_modifier_rounds: 2
  # Buffer size for audio processing (in samples)
  audio_buffer_size: 8192

# Audio effect parameters
audio_effects:
  # Volume boost for 'loud' effect (in dB)
  loud_boost_db: 6.0
  # Speed multiplier for 'fast' effect
  fast_speed_multiplier: 1.5
  # Speed multiplier for 'slow' effect  
  slow_speed_multiplier: 0.75
  # Pitch shift for 'up' effect (in cents, 100 cents = 1 semitone)
  pitch_up_cents: 200
  # Pitch shift for 'down' effect (in cents, negative values lower pitch)
  pitch_down_cents: -200
  # Bass boost frequency for 'bass' effect (in Hz)
  bass_boost_frequency_hz: 50
  # Bass boost gain for 'bass' effect (in dB)
  bass_boost_gain_db: 25.0
  # Reverb room size (0.0-1.0, larger = more reverb)
  reverb_room_size: 0.5
  # Reverb damping (0.0-1.0, higher = less bright reverb)
  reverb_damping: 0.5
  # Echo delay time (in milliseconds)
  echo_delay_ms: 300
  # Echo feedback amount (0.0-1.0, higher = more repeats)
  echo_feedback: 0.3

# File and directory paths
paths:
  # Directory to store bot data (sounds, database, certificates, etc.)
  # If null, defaults to ~/.bigbot
  data_dir: null
  # Path to SSL certificate file (if null, uses data_dir/cert.pem)
  cert_file: null
  # Path to SSL private key file (if null, uses data_dir/key.pem)  
  key_file: null
  # Directory for trusted server certificates (if null, uses data_dir/trusted_certificates)
  trusted_certs_dir: null
